from psychopy import visual, core, event, gui, data
import os, random, pandas as pd

# -------------------------------------------------------------------------
# 1. Setup & Demographics
# -------------------------------------------------------------------------
exp_info = {
    'Participant ID': '',
    'Session Type': ['Ind', 'Col'],
    'Gender': ['Male', 'Female', 'Non-binary', 'N/A'],
    'Age': '',
    'Session Order': ['Ind-Col', 'Col-Ind']
}

dlg = gui.DlgFromDict(dictionary=exp_info, title='Experiment Setup',
                      order=['Participant ID', 'Session Type', 'Gender', 'Age', 'Session Order'])
if not dlg.OK: core.quit()

# Pathing
if not os.path.exists('data'): os.makedirs('data')
data_filename = f"data/{exp_info['Participant ID']}_{exp_info['Session Type']}_{data.getDateStr()}.csv"
image_folder = 'Pilot_selected_images'
stimuli_csv = 'pilot_stimuli_48_final.csv'

try:
    stim_df = pd.read_csv(stimuli_csv)
    stim_df = stim_df.sample(frac=1).reset_index(drop=True)
except Exception as e:
    print(f"Error: Could not find {stimuli_csv}. {e}")
    core.quit()

# -------------------------------------------------------------------------
# 2. Window & UI Setup
# -------------------------------------------------------------------------
win = visual.Window(fullscr=True, monitor="testMonitor", units="height", color=[0.9, 0.9, 0.9])
text_color = [-1, -1, -1] # Black
font_type = 'Arial'

# Stimuli definitions
stim_image = visual.ImageStim(win, size=(0.7, 0.7)) 
instr_text = visual.TextStim(win, height=0.03, color=text_color, wrapWidth=1.2, font=font_type)
resp_prompt = visual.TextStim(win, text="Is this a real image or generated by AI?", 
                              pos=(0, 0.3), height=0.04, color=text_color, font=font_type)

# UI Elements (Arrows)
arrow_vertices = [(0,0.02), (0.1,0.02), (0.1,0.05), (0.15,0), (0.1, -0.05), (0.1, -0.02), (0, -0.02)]
arrow_left = visual.ShapeStim(win, vertices=arrow_vertices, ori=180, fillColor=text_color, lineColor=text_color, pos=(-0.2, 0))
arrow_right = visual.ShapeStim(win, vertices=arrow_vertices, ori=0, fillColor=text_color, lineColor=text_color, pos=(0.2, 0))
label_left = visual.TextStim(win, text="", pos=(-0.4, 0), height=0.045, color=text_color, font=font_type)
label_right = visual.TextStim(win, text="", pos=(0.4, 0), height=0.045, color=text_color, font=font_type)

# Confidence Elements
conf_prompt = visual.TextStim(win, text="How confident are you?", pos=(0, 0.25), height=0.045, color=text_color, font=font_type)
slider = visual.Slider(win, ticks=(1, 2, 3, 4, 5, 6, 7), labels=None, 
                       granularity=1, style='rating', pos=(0, -0.1), size=(0.9, 0.05),
                       markerColor=text_color, lineColor=text_color, font=font_type)

label_lowest = visual.TextStim(win, text="Lowest", pos=(-0.45, -0.18), height=0.035, 
                               color=text_color, font=font_type, bold=True)
label_highest = visual.TextStim(win, text="Highest", pos=(0.45, -0.18), height=0.035, 
                                color=text_color, font=font_type, bold=True)

# --- Progress Bar Setup ---
bar_width = 0.8
bar_height = 0.02
bar_pos_y = -0.45
# Outline: Black border, background-colored fill
progress_outline = visual.Rect(win, width=bar_width, height=bar_height, pos=(0, bar_pos_y), 
                               lineColor=text_color, fillColor=[0.9, 0.9, 0.9], lineWidth=2)
# Fill: Green
progress_fill = visual.Rect(win, width=0, height=bar_height, pos=(-bar_width/2, bar_pos_y), 
                            fillColor=[-0.4, 0.4, -0.4], lineColor=None)

def draw_progress(current_trial, total_trials):
    """Updates and draws the progress bar."""
    fill_width = (current_trial / total_trials) * bar_width
    progress_fill.width = fill_width
    # Shift position so it grows from the left
    progress_fill.pos = ((-bar_width/2) + (fill_width/2), bar_pos_y)
    progress_outline.draw()
    progress_fill.draw()

# Thank You Screen
thanks_text = visual.TextStim(win, text="This is the end of experiment, thank you so much for participating!", 
                              height=0.04, color=text_color, font=font_type, wrapWidth=1.2)

# -------------------------------------------------------------------------
# 3. Balanced Conditional Instructions
# -------------------------------------------------------------------------
welcome_line = "Welcome to the experiment!\n\n"
common_rules = (
    "Human faces will appear one by one for 5 seconds each.\n"
    "Try to be as accurate as you can.\n\n"
)

if exp_info['Session Type'] == 'Ind':
    instr_msg = welcome_line + (
        "You will play a classification game.\n" +
        common_rules +
        "After each face, decide if it was a real human or generated by AI\n"
        "using the arrow keys. Finally, rate your confidence level.\n\n"
        "Press SPACE to begin."
    )
else:
    instr_msg = welcome_line + (
        "You will be playing a game together as a group.\n" +
        common_rules +
        "As a group, you must reach a consensus for each choice.\n"
        "One person will then indicate the group decision and confidence level.\n\n"
        "Press SPACE to begin."
    )

# -------------------------------------------------------------------------
# 4. Trial Loop
# -------------------------------------------------------------------------
trial_results = []
total_trials = len(stim_df)

try:
    instr_text.text = instr_msg
    instr_text.draw()
    win.flip()
    if 'escape' in event.waitKeys(keyList=['space', 'escape']): core.quit()

    for index, row in stim_df.iterrows():
        img_filename = row['Filename']
        parts = img_filename.split('.')
        img_type, img_race, img_gender = parts[1], parts[2], parts[3]
        
        stim_image.image = os.path.join(image_folder, img_filename)
        
        # --- PHASE 1: STIMULUS (5s) ---
        stim_timer = core.Clock()
        while stim_timer.getTime() < 5.0:
            stim_image.draw()
            draw_progress(index, total_trials) # index starts at 0, shows progress done so far
            win.flip()
            if 'escape' in event.getKeys(): raise KeyboardInterrupt 
            core.wait(0.01)
        
        # --- PHASE 2: BINARY RESPONSE ---
        if random.choice([True, False]):
            left_txt, right_txt = "AI", "Real"
        else:
            left_txt, right_txt = "Real", "AI"
            
        label_left.text = left_txt
        label_right.text = right_txt
        
        resp_prompt.draw()
        arrow_left.draw()
        arrow_right.draw()
        label_left.draw()
        label_right.draw()
        draw_progress(index, total_trials)
        win.flip()
        
        rt_clock = core.Clock()
        event.clearEvents()
        keys = event.waitKeys(keyList=['left', 'right', 'escape'], timeStamped=rt_clock)
        
        if 'escape' in keys[0]: raise KeyboardInterrupt
        
        button_pressed = keys[0][0]
        rt_ms = keys[0][1] * 1000
        final_choice = left_txt if button_pressed == 'left' else right_txt
        
        # --- PHASE 3: CONFIDENCE ---
        slider.reset()
        slider.markerPos = 4 
        moved = False 
        while True:
            conf_prompt.draw()
            label_lowest.draw()
            label_highest.draw()
            slider.draw()
            draw_progress(index, total_trials)
            win.flip()
            
            c_keys = event.getKeys(keyList=['left', 'right', 'space', 'escape'])
            if 'escape' in c_keys: raise KeyboardInterrupt
            elif 'left' in c_keys:
                slider.markerPos = max(1, slider.markerPos - 1)
                moved = True
            elif 'right' in c_keys:
                slider.markerPos = min(7, slider.markerPos + 1)
                moved = True
            elif 'space' in c_keys and moved:
                confidence = slider.markerPos
                break

        # --- LOGGING (Demographics FIRST) ---
        is_correct = 1 if (final_choice == "Real" and img_type == "R") or (final_choice == "AI" and img_type == "S") else 0
        
        # We start the dictionary with exp_info to put them in the leftmost columns
        data_row = {k: v for k, v in exp_info.items()}
        data_row.update({
            'Trial': index + 1,
            'Filename': img_filename,
            'Parsed_Type': img_type,
            'Parsed_Race': img_race,
            'Parsed_Gender': img_gender,
            'Difficulty_Group': row['Group'],
            'Left_Side_Label': left_txt,
            'Right_Side_Label': right_txt,
            'Button_Pressed': button_pressed,
            'Final_Choice': final_choice,
            'Correct': is_correct,
            'RT_ms': rt_ms,
            'Confidence': confidence
        })
        trial_results.append(data_row)

    # Final Progress Bar State (100% full)
    draw_progress(total_trials, total_trials)
    thanks_text.draw()
    win.flip()
    core.wait(3.0)

finally:
    if len(trial_results) > 0:
        pd.DataFrame(trial_results).to_csv(data_filename, index=False)
        print(f"Data saved for {len(trial_results)} trials: {data_filename}")
    win.close()
    core.quit()